///|
pub const EPERM : Int = 1

///|
pub const ENOENT : Int = 2

///|
pub const ESRCH : Int = 3

///|
pub const EINTR : Int = 4

///|
pub const EIO : Int = 5

///|
pub const ENXIO : Int = 6

///|
pub const E2BIG : Int = 7

///|
pub const ENOEXEC : Int = 8

///|
pub const EBADF : Int = 9

///|
pub const ECHILD : Int = 10

///|
pub const EAGAIN : Int = 11

///|
pub const ENOMEM : Int = 12

///|
pub const EACCES : Int = 13

///|
pub const EFAULT : Int = 14

///|
pub const ENOTBLK : Int = 15

///|
pub const EBUSY : Int = 16

///|
pub const EEXIST : Int = 17

///|
pub const EXDEV : Int = 18

///|
pub const ENODEV : Int = 19

///|
pub const ENOTDIR : Int = 20

///|
pub const EISDIR : Int = 21

///|
pub const EINVAL : Int = 22

///|
pub const ENFILE : Int = 23

///|
pub const EMFILE : Int = 24

///|
pub const ENOTTY : Int = 25

///|
pub const ETXTBSY : Int = 26

///|
pub const EFBIG : Int = 27

///|
pub const ENOSPC : Int = 28

///|
pub const ESPIPE : Int = 29

///|
pub const EROFS : Int = 30

///|
pub const EMLINK : Int = 31

///|
pub const EPIPE : Int = 32

///|
pub const EDOM : Int = 33

///|
pub const ERANGE : Int = 34

///|
pub const EWOULDBLOCK : Int = EAGAIN

///|
pub const EDEADLK : Int = 35

///|
pub const ENAMETOOLONG : Int = 36

///|
pub const ENOLCK : Int = 37

///|
pub const ENOSYS : Int = 38

///|
pub const ENOTEMPTY : Int = 39

///|
pub const ELOOP : Int = 40

///|
pub const ENOMSG : Int = 42

///|
pub const EIDRM : Int = 43

///|
pub const ECHRNG : Int = 44

///|
pub const EL2NSYNC : Int = 45

///|
pub const EL3HLT : Int = 46

///|
pub const EL3RST : Int = 47

///|
pub const ELNRNG : Int = 48

///|
pub const EUNATCH : Int = 49

///|
pub const ENOCSI : Int = 50

///|
pub const EL2HLT : Int = 51

///|
pub const EBADE : Int = 52

///|
pub const EBADR : Int = 53

///|
pub const EXFULL : Int = 54

///|
pub const ENOANO : Int = 55

///|
pub const EBADRQC : Int = 56

///|
pub const EBADSLT : Int = 57

///|
pub const EMULTIHOP : Int = 72

///|
pub const EOVERFLOW : Int = 75

///|
pub const ENOTUNIQ : Int = 76

///|
pub const EBADFD : Int = 77

///|
pub const EBADMSG : Int = 74

///|
pub const EREMCHG : Int = 78

///|
pub const ELIBACC : Int = 79

///|
pub const ELIBBAD : Int = 80

///|
pub const ELIBSCN : Int = 81

///|
pub const ELIBMAX : Int = 82

///|
pub const ELIBEXEC : Int = 83

///|
pub const EILSEQ : Int = 84

///|
pub const ERESTART : Int = 85

///|
pub const ESTRPIPE : Int = 86

///|
pub const EUSERS : Int = 87

///|
pub const ENOTSOCK : Int = 88

///|
pub const EDESTADDRREQ : Int = 89

///|
pub const EMSGSIZE : Int = 90

///|
pub const EPROTOTYPE : Int = 91

///|
pub const ENOPROTOOPT : Int = 92

///|
pub const EPROTONOSUPPORT : Int = 93

///|
pub const ESOCKTNOSUPPORT : Int = 94

///|
pub const EOPNOTSUPP : Int = 95

///|
pub const EPFNOSUPPORT : Int = 96

///|
pub const EAFNOSUPPORT : Int = 97

///|
pub const EADDRINUSE : Int = 98

///|
pub const EADDRNOTAVAIL : Int = 99

///|
pub const ENETDOWN : Int = 100

///|
pub const ENETUNREACH : Int = 101

///|
pub const ENETRESET : Int = 102

///|
pub const ECONNABORTED : Int = 103

///|
pub const ECONNRESET : Int = 104

///|
pub const ENOBUFS : Int = 105

///|
pub const EISCONN : Int = 106

///|
pub const ENOTCONN : Int = 107

///|
pub const ESHUTDOWN : Int = 108

///|
pub const ETOOMANYREFS : Int = 109

///|
pub const ETIMEDOUT : Int = 110

///|
pub const ECONNREFUSED : Int = 111

///|
pub const EHOSTDOWN : Int = 112

///|
pub const EHOSTUNREACH : Int = 113

///|
pub const EALREADY : Int = 114

///|
pub const EINPROGRESS : Int = 115

///|
pub const ESTALE : Int = 116

///|
pub const EDQUOT : Int = 122

///|
pub const ENOMEDIUM : Int = 123

///|
pub const EMEDIUMTYPE : Int = 124

///|
pub const ECANCELED : Int = 125

///|
pub const ENOKEY : Int = 126

///|
pub const EKEYEXPIRED : Int = 127

///|
pub const EKEYREVOKED : Int = 128

///|
pub const EKEYREJECTED : Int = 129

///|
pub const EOWNERDEAD : Int = 130

///|
pub const ENOTRECOVERABLE : Int = 131

///|
pub const EHWPOISON : Int = 133

///|
pub const ERFKILL : Int = 132
